baseURL: "https://your-site-url.com/"
languageCode: en-us
title: "Samson Ajadalu"
theme: "CustomPaperMod"

menu:
  main:
    - identifier: home
      name: Home
      url: /
      weight: 10
    - identifier: blog
      name: Blog
      url: /blog
      weight: 20
    - identifier: projects
      name: Projects
      url: /projects
      weight: 30
    - identifier: experience
      name: Experience
      url: /experience
      weight: 40
    - identifier: search
      name: Search
      url: /search
      weight: 50

params:
  showToc: true
  TocOpen: false
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  hideMeta: false

  env: production

  profileMode:
    enabled: true
    title: "Samson Ajadalu"
    subtitle: "Hi 👋 I’m Samson Ajadalu, an Aspiring AI + Automation Engineer."
    imageUrl: "home/casual-small-square.jpeg"
    imageWidth: 220
    imageHeight: 220

outputs:
  home:
    - HTML
    - RSS
    - JSON

markup:
  goldmark:
    renderer:
      unsafe: true
